version: '3'
services:

  #PHP Service
  python_app:
    build: ./docker/python/
    container_name: python_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: python_app
      SERVICE_TAGS: dev
      MY_SQL_IP: python_db
    links:
      - python_db 
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    ports:
      - "8888:8888"
    networks:
      - python-machinelearning-network
  python_db:
    image: mysql:5.7.22
    container_name: python_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: python_machine_learning
      MYSQL_ROOT_PASSWORD: 123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - python-machinelearning-network
  python_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: python_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "8088:80"
    depends_on:
      - python_db
    networks:
        - python-machinelearning-network
#Docker Networks
networks:
  python-machinelearning-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
